

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { Toaster } from 'sonner'
  // import NotificationPage from "@/components/notfications";
import { supabase } from "@/lib/supabase";
import { Session } from "@supabase/supabase-js";
import ScrollProgressBar from "@/components/scroll-progress-bar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen">
          <Sidebar />
          <main className="flex-1 overflow-auto relative">
            <ScrollProgressBar />
            <div className="h-full overflow-auto">
              {children}
            </div>
            <Toaster position="top-right" richColors={true} />
          </main>
        </div>
      </body>
    </html>
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //   <div className="flex h-screen">
    //        <Sidebar />
          


    //       <main className="flex-1 overflow-auto">
    //         <ScrollProgressBar />
    //         {children}
    //         <Toaster position="top-right" richColors={true} />
    //       </main>
    //       {/* <NotificationPage/> */}
    //      </div>
    //   </body>
    // </html>
  );
}
