import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { Toaster } from 'sonner'
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";
import NotificationPage from "@/components/notfications";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex h-screen">
      <SessionProvider session={session}>
          <Sidebar />
          
          <main className="flex-1 overflow-auto">
            {children}
            <Toaster position="top-right" richColors={true} />
          </main>
          {/* <NotificationPage/> */}
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
